project:
  type: book
  output-dir: docs

book:
  title: "Social Data Science"
  subtitle: "Core Technologies and Applications"
  author: "Edgar J. Treischl"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/edgar-treischl/core_technologies
        aria-label: GitHub


bibliography: references.bib
cover-image: cover.png

format:
  html:
    theme: litera
    include-in-header: 
      - progress-bar.html
  pdf:
    documentclass: scrreprt
    highlight-style: kate



